### ISSUE TITLE
Possible incompatibility with 6.7.1

### ISSUE THREAD

**Issue by widhalmt** [Icinga/logstash-output-icinga#11]
Hi,

We got the output working with Logstash 6.4 but not with 6.7.1. Could you please check if there's some incompatibility between the output und Logstash 6.7.1?

Here are the error messages:

```
[2019-04-10T18:12:23,808][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Reload/pipeline_id:oracle, :exception=>"SyntaxError", :message=>"/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-icinga-1.2.1/lib/logstash/outputs/icinga.rb:383: Invalid next", :backtrace=>["org/jruby/RubyClass.java:233:in `allocate'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:232:in `initialize'", "org/logstash/config/ir/compiler/OutputDelegatorExt.java:48:in `initialize'", "org/logstash/config/ir/compiler/OutputDelegatorExt.java:30:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:239:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:184:in `plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):147:in `initialize'", "org/jruby/RubyKernel.java:1047:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-co
 re/lib/logstash/pipeline_action/reload.rb:43:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:96:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:165:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:96:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:39:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:334:in `block in converge_state'"]}
```

Thanks.

**Comment by widhalmt** [comment]
ref/NC/558885

**Comment by bobapple** [comment]
Moved to https://github.com/logstash-plugins/logstash-output-icinga/issues/3
